services:
  - type: web
    name: complainer-api
    env: node
    plan: free
    region: oregon
    rootDir: .
    buildCommand: npm ci && npm run build && ls -la dist/
    startCommand: node ./dist/index.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000